org: bibliokuna
service: api-reservations

custom:
  URLS:
    users:
      dev: https://39huieajj1.execute-api.us-east-1.amazonaws.com/dev
      test: https://6w6n4rcfl7.execute-api.us-east-1.amazonaws.com/test
      prod: https://jidj42yv4h.execute-api.us-east-1.amazonaws.com/prod
    books:
      dev: https://vtmz9bppzb.execute-api.us-east-1.amazonaws.com/dev
      test: https://ka0lzpltya.execute-api.us-east-1.amazonaws.com/test
      prod: https://2t3xvsitr4.execute-api.us-east-1.amazonaws.com/prod
    libraries:
      dev: https://2333ibrncl.execute-api.us-east-1.amazonaws.com/dev     
      test: https://78v835l8h4.execute-api.us-east-1.amazonaws.com/test
      prod: https://836c1esai1.execute-api.us-east-1.amazonaws.com/prod
    environments:
      dev: https://lsxyzj9yxe.execute-api.us-east-1.amazonaws.com/dev
      test: https://p926quyct1.execute-api.us-east-1.amazonaws.com/test
      prod: https://odal3bx0kc.execute-api.us-east-1.amazonaws.com/prod

provider:
  name: aws
  runtime: python3.12
  memorySize: 1024
  timeout: 30
  iam:
    role: ${env:LAB_ROLE_ARN}
  environment:
    RESERVATIONS_TABLE_NAME: ${sls:stage}-t_reservations
    USERS_URL: ${self:custom.URLS.users.${sls:stage}}
    BOOKS_URL: ${self:custom.URLS.books.${sls:stage}}
    LIBRARIES_URL: ${self:custom.URLS.libraries.${sls:stage}}
    ENVIRONMENTS_URL: ${self:custom.URLS.environments.${sls:stage}}

functions:
  GetBookReservations:
    handler: GetBookReservations.lambda_handler
    events:
      - http:
          path: reservation/book
          method: get
          cors: true
          integration: lambda

  GetEnvironmentReservations:
    handler: GetEnvironmentReservations.lambda_handler
    events:
      - http:
          path: reservation/environment
          method: get
          cors: true
          integration: lambda

  ReserveBook:
    handler: ReserveBook.lambda_handler
    events:
      - http:
          path: reservation/book
          method: post
          cors: true
          integration: lambda

  ReserveEnvironment:
    handler: ReserveEnvironment.lambda_handler
    events:
      - http:
          path: reservation/environment
          method: post
          cors: true
          integration: lambda

resources:
  Resources:
    ReservationsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.RESERVATIONS_TABLE_NAME}
        AttributeDefinitions:
          - AttributeName: tenant_id#email
            AttributeType: S
          - AttributeName: type
            AttributeType: S
          - AttributeName: res_id
            AttributeType: S
          - AttributeName: status
            AttributeType: S
          - AttributeName: tenant_id#type
            AttributeType: S
          - AttributeName: email#status
            AttributeType: S
          - AttributeName: max_return_date#status
            AttributeType: S
        
        KeySchema:
          - AttributeName: tenant_id#email
            KeyType: HASH
          - AttributeName: res_id
            KeyType: RANGE

        GlobalSecondaryIndexes:
          - IndexName: "tenant_id-type_GSI"
            KeySchema:
              - AttributeName: "tenant_id#type"
                KeyType: "HASH"
              - AttributeName: "email#status"
                KeyType: "RANGE"
            Projection:
              ProjectionType: "ALL"

        LocalSecondaryIndexes:
          - IndexName: "type_LSI"
            KeySchema:
              - AttributeName: "tenant_id#email"
                KeyType: "HASH"
              - AttributeName: "type"
                KeyType: "RANGE"
            Projection:
              ProjectionType: "ALL"
          - IndexName: "status_LSI"
            KeySchema:
              - AttributeName: "tenant_id#email"
                KeyType: "HASH"
              - AttributeName: "status"
                KeyType: "RANGE"
            Projection:
              ProjectionType: "ALL"
          - IndexName: "max_return_date-status_LSI"
            KeySchema:
              - AttributeName: "tenant_id#email"
                KeyType: "HASH"
              - AttributeName: "max_return_date#status"
                KeyType: "RANGE"
            Projection:
              ProjectionType: "ALL"

        BillingMode: PAY_PER_REQUEST
