functions:
  createLibrary:
    handler: createLibrary.handler
    events:
      - http:
          path: /libraries
          method: post
          cors: true
          integration: lambda

  getLibraryInfo:
    handler: getLibraryInfo.handler
    events:
      - http:
          path: /libraries/info
          method: get
          cors: true
          integration: lambda
          request:
            parameters:
              querystrings:
                tenant_id: true

  getAllLibraries:
    handler: getAllLibraries.handler
    events:
      - http:
          path: /libraries/all
          method: get
          cors: true
          integration: lambda

  getLibraryCustomization:
    handler: getLibraryCustomization.handler
    events:
      - http:
          path: /libraries/customization
          method: get
          cors: true
          integration: lambda
          request:
            parameters:
              querystrings:
                tenant_id: true
