org: bibliokuna
service: api-libraries

custom:
  URLS:
    users:
      dev: https://yqyomo3gcf.execute-api.us-east-1.amazonaws.com/dev
      test:
      prod:

provider:
  name: aws
  runtime: nodejs18.x
  memorySize: 1024
  timeout: 30
  iam:
    role: ${env:LAB_ROLE_ARN}
  environment:
    TABLE_NAME: ${sls:stage}-t_libraries
    USERS_URL: ${self:custom.URLS.users.${sls:stage}}

functions:
  createLibrary:
    handler: createLibrary.handler
    events:
      - http:
          path: /libraries
          method: post
          cors: true
          integration: lambda

  getLibraryInfo:
    handler: getLibraryInfo.handler
    events:
      - http:
          path: /libraries/info
          method: get
          cors: true
          integration: lambda

  getAllLibraries:
    handler: getAllLibraries.handler
    events:
      - http:
          path: /libraries/all
          method: get
          cors: true
          integration: lambda

  getLibraryCustomization:
    handler: getLibraryCustomization.handler
    events:
      - http:
          path: /libraries/customization
          method: get
          cors: true
          integration: lambda
          request:
            parameters:
              querystrings:
                tenant_id: true

resources:
  Resources:
    TablaLibraries:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.TABLE_NAME}
        AttributeDefinitions:
          - AttributeName: tenant_id
            AttributeType: S
        KeySchema:
          - AttributeName: tenant_id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
