org: bibliokuna
service: api-favorites

custom:
  URLS:
    users:
      dev: https://39huieajj1.execute-api.us-east-1.amazonaws.com/dev
      test: https://6w6n4rcfl7.execute-api.us-east-1.amazonaws.com/test
      prod: https://jidj42yv4h.execute-api.us-east-1.amazonaws.com/prod

provider:
  name: aws
  runtime: nodejs18.x
  memorySize: 1024
  timeout: 30
  iam:
    role: ${env:LAB_ROLE_ARN}
  environment:
    FAVORITES_TABLE_NAME: ${sls:stage}-t_favorites
    USERS_URL: ${self:custom.URLS.users.${sls:stage}}

functions:
  addOrUpdateFavorite:
    handler: addOrUpdateFavorite.handler
    events:
      - http:
          path: /favorite
          method: post
          cors: true
          integration: lambda

  getActualFavorites:
    handler: getActualFavorites.handler
    events:
      - http:
          path: /favorite/my/actual
          method: get
          cors: true
          integration: lambda

  getAllFavorites:
    handler: getAllFavorites.handler
    events:
      - http:
          path: /favorite/my/all
          method: get
          cors: true
          integration: lambda

resources:
  Resources:
    FavoritesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.FAVORITES_TABLE_NAME}
        AttributeDefinitions:
          - AttributeName: tenant_id
            AttributeType: S
          - AttributeName: email#isbn
            AttributeType: S
        KeySchema:
          - AttributeName: tenant_id
            KeyType: HASH
          - AttributeName: email#isbn
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
