org: ginodaza
service: api-libraries

provider:
  name: aws
  runtime: python3.12
  memorySize: 1024
  timeout: 30
  iam:
    role: ${env:LAB_ROLE_ARN}
  environment:
    USERS_TABLE_NAME: t_usuario
    CODES_TABLE_NAME: codes_table
    TOKENS_TABLE_NAME: t_tokens_acceso

functions:
  CreateCode:
    handler: CreateCode.lambda_handler
    events:
      - http:
          path: codes/create
          method: get
          cors: true
          integration: lambda

  GetCodes:
    handler: GetCodes.lambda_handler
    events:
      - http:
          path: codes
          method: get
          cors: true
          integration: lambda

  CreateUser:
    handler: CreateUser.lambda_handler
    events:
      - http:
          path: users/create
          method: post
          cors: true
          integration: lambda

  Login:
    handler: Login.lambda_handler
    events:
      - http:
          path: login
          method: post
          cors: true
          integration: lambda

  ValidateToken:
    handler: ValidateToken.lambda_handler
    events:
      - http:
          path: validate-token
          method: get
          cors: true
          integration: lambda

resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.USERS_TABLE_NAME}
        AttributeDefinitions:
          - AttributeName: tenant_id
            AttributeType: S
          - AttributeName: email
            AttributeType: S
        KeySchema:
          - AttributeName: tenant_id
            KeyType: HASH
          - AttributeName: email
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST

    TokensTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.TOKENS_TABLE_NAME}
        AttributeDefinitions:
          - AttributeName: tenant_id
            AttributeType: S
          - AttributeName: token
            AttributeType: S
        KeySchema:
          - AttributeName: tenant_id
            KeyType: HASH
          - AttributeName: token
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST

    CodesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.CODES_TABLE_NAME}
        AttributeDefinitions:
          - AttributeName: tenant_id
            AttributeType: S
          - AttributeName: code
            AttributeType: S
        KeySchema:
          - AttributeName: tenant_id
            KeyType: HASH
          - AttributeName: code
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
