org: bibliokuna
service: api-books

custom:
  URLS:
    users:
      dev: https://yqyomo3gcf.execute-api.us-east-1.amazonaws.com/dev
      test: 
      prod: 
    favorites:
      dev: https://8xpkki1r6a.execute-api.us-east-1.amazonaws.com/${sls:stage}
      test: 
      prod: 

provider:
  name: aws
  runtime: python3.12
  memorySize: 1024
  timeout: 30
  iam:
    role: ${env:LAB_ROLE_ARN}
  environment:
    TABLE_NAME: ${sls:stage}-t_books
    FAVORITES_URL: ${self:custom.URLS.favorites.${sls:stage}}
    USERS_URL: ${self:custom.URLS.users.${sls:stage}}

functions:
  createBook:
    handler: CreateBook.lambda_handler
    events:
      - http:
          path: /books/create/single
          method: post
          cors: true
          integration: lambda

  createBooks:
    handler: CreateBooks.lambda_handler
    events:
      - http:
          path: /books/create/books
          method: post
          cors: true
          integration: lambda

  searchBooks:
    handler: SearchBooks.lambda_handler
    events:
      - http:
          path: /books/search
          method: get
          cors: true
          integration: lambda

  getBooksByIsbns:
    handler: GetBooksByIsbns.lambda_handler
    events:
      - http:
          path: /books/details
          method: get
          cors: true
          integration: lambda
          
  reduceStockByIsbn:
    handler: ReduceStockByIsbn.lambda_handler
    events:
      - http:
          path: /books/stock
          method: patch
          cors: true
          integration: lambda

resources:
  Resources:
    TablaLibros:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.TABLE_NAME}
        AttributeDefinitions:
          - AttributeName: tenant_id
            AttributeType: S
          - AttributeName: isbn
            AttributeType: S
          - AttributeName: title_index
            AttributeType: S
          - AttributeName: author_name_index
            AttributeType: S
          - AttributeName: author_lastname_index
            AttributeType: S
        KeySchema:
          - AttributeName: tenant_id
            KeyType: HASH
          - AttributeName: isbn
            KeyType: RANGE
        LocalSecondaryIndexes:
          - IndexName: title-index
            KeySchema:
              - AttributeName: tenant_id
                KeyType: HASH
              - AttributeName: title_index
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
          - IndexName: author_name-index
            KeySchema:
              - AttributeName: tenant_id
                KeyType: HASH
              - AttributeName: author_name_index
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
          - IndexName: author_lastname-index
            KeySchema:
              - AttributeName: tenant_id
                KeyType: HASH
              - AttributeName: author_lastname_index
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
        BillingMode: PAY_PER_REQUEST
