org: bibliokuna
service: api-emails

provider:
  name: aws
  runtime: nodejs18.x
  memorySize: 1024
  timeout: 30
  iam:
    role: ${env:LAB_ROLE_ARN} 
  environment:
    GMAIL_USER: bibliokuna@gmail.com 
    GMAIL_PASS: lxjg aujr whey ghby 

functions:
  sendEmail:
    handler: sendRegistration.handler 
    events:
      - http:
          path: /emails/registration 
          method: post       
          cors: true        
          integration: lambda
  sendSignUp:
    handler: sendSignUp.handler
    events:
      - http:
          path: /emails/signUp
          method: post
          cors: true
          integration: lambda
package:
  include:
    - sendRegistration.html # Include the HTML template in the deployment package
    - sendSignUp.html