org: bibliokuna
service: api-emails

provider:
  name: aws
  runtime: nodejs18.x
  memorySize: 1024
  timeout: 30
  iam:
    role: ${env:LAB_ROLE_ARN}
  environment:
    TABLE_NAME: ${sls:stage}-t_notifications
    GMAIL_USER: bibliokuna@gmail.com
    GMAIL_PASS: lxjg aujr whey ghby

functions:
  sendEmail:
    handler: sendRegistration.handler
    events:
      - http:
          path: /emails/registration
          method: post
          cors: true
          integration: lambda
  sendSignUp:
    handler: sendSignUp.handler
    events:
      - http:
          path: /emails/signUp
          method: post
          cors: true
          integration: lambda

resources:
  Resources:
    EmailsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: TableName: ${self:provider.environment.TABLE_NAME}
        AttributeDefinitions:
          - AttributeName: tenant_id
            AttributeType: S
          - AttributeName: email
            AttributeType: S
        KeySchema:
          - AttributeName: tenant_id
            KeyType: HASH # Partition Key
          - AttributeName: email
            KeyType: RANGE # Sort Key
        BillingMode: PAY_PER_REQUEST # On-demand billing
        

package:
  include:
    - sendRegistration.html # Include the HTML template in the deployment package
    - sendSignUp.html
